### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Faam2000** [colinzhaoxp/CDSM#4]
hi, thanks for the implementation. I have this error : /war/spool/torque/mom_priv/jobs/hpc,SC; Segmentation fault. how can I fix it? I think it is about the memory using in the framework.

**Comment by colinzhaoxp** [comment]
sorry, I didn't meet this error.
there are two suggestions that I can give:
1. Debug the code and find the place where the happened error.
2. Maybe you should paste more information about this error.
